### ISSUE TITLE
clear SEL log fail

### ISSUE THREAD

**Issue by CassieDan7Song** [DMTF/Redfish-Tacklebox#41] opened 2020-06-12 08:17 UTC
Clear SEL log failed with body={} in logs.py in redfish_utiltiles module.
# Clear the log
    response = context.post( clear_uri, body = {} )
    verify_response( response )
    return response

The correct body is body = {"ClearType": "ClearAll"}  according to spec in MegaRAC Redfish API follows DSP0266 1.7.0 Specification and Redfish Schema 2019.1.

And clear log succeed after change to code. 
Please help have a check and fix this issue. Thanks very much.

**Comment by mraineri** [comment] 2020-06-12 09:54
That's not following the scheme definition of the LogService published by the DMTF.

This is the action definition found in LogService_v1.xml: https://redfish.dmtf.org/schemas/LogService_v1.xml

```
<Action Name="ClearLog" IsBound="true">
  <Parameter Name="LogService" Type="LogService.v1_0_0.Actions"/>
  <Annotation Term="OData.Description" String="The action to clear the log for this Log Service."/>
  <Annotation Term="OData.LongDescription" String="This action shall delete all entries found in the Entries collection for this Log Service."/>
</Action>
```

There is no "ClearType" parameter. The DMTF has never published this action with any parameters. It appears the implementation you're working with is illegally modifying the action definition.

**Comment by mraineri** [comment] 2020-06-25 19:28
@CassieDan7Song were you able to follow up with your vendor to fix the issue with their non-conformance with the standard?

**Comment by mraineri** [comment] 2020-09-18 18:51
Closing; no further feedback, and the issue is with a non-conformant implementation. If there are other issues, please let us know.

**Closed** 2020-09-18 18:52 UTC
Labels: cleanup
