### ISSUE TITLE
rf_sensor_list.py script, does not identify the correct fan fault

### ISSUE THREAD

**Issue by palrap** [DMTF/Redfish-Tacklebox#148] opened 2024-04-16 19:01 UTC
Executed rf_sensor_list.py on a system with a fan fault.  The script indicated tach faults across two different fan packs, although the error was within one fan pack.  Used thmtest and SEL check, both of which indicated the correct fan fault.  Injected fan faults by simply removing a fan to see how the error was reported. Attached error reporting.
[rf_sensor_list.txt](https://github.com/DMTF/Redfish-Tacklebox/files/15001492/rf_sensor_list.txt)

**Comment by mraineri** [comment] 2024-04-16 20:29
You would need to contact your system vendor. It looks like they are not mapping their fans properly in their implementation.

**Comment by mraineri** [comment] 2024-04-23 13:56
Closing; confirmed with the submitter that this is an issue with the implementation.

**Closed by mraineri** 2024-04-23 13:56 UTC
